PC_MODE = False
FLASK_ENABLED= False

SENSOR_CONFIGURED = "TILT_B_INCL"  # "TILT_A_INCL"

URL_ONTOLOGY_DEPLOYMENT_LOCAL = "http://localhost:5000"
URL_ONTOLOGY_DEPLOYMENT_CLOUD = "/api" #"http://35.195.86.253"

ONTOLOGY_SENSOR_NAME = "Tilt 6Axis B Inclination"
ONTOLOGY_OBSERVABLE_PROPERTY = "Inclination"
